Member registration form
stephtkd/tkkd pull request #130
Opened 2023-02-02 16:24 UTC by Anthony-Boulch-Celad

Mise en place de la base du formulaire d'inscription de membre.

Le but est de faire le point + démo pour partir sur une bonne base pour la suite des tickets.

2023-02-03 10:15 UTC, guillaumeprost commented on templates/member_registration/register.html.twig
> +                                        <p>Prénom : <strong>{{current_user.firstName}}</strong></p>
Tu peux faire un app.user.firstName

2023-02-03 10:23 UTC, guillaumeprost requested changes

2023-02-03 10:23 UTC, guillaumeprost commented on src/Controller/MemberRegistrationController.php
> +        $user = [
Tu n'as pas besoin de passer par un tableau

2023-02-03 10:23 UTC, guillaumeprost commented on src/Controller/MemberRegistrationController.php
> +            'current_user' => $user
Tu peux accéder au user depuis le twig, comme je t'ai mis en commentaire

2023-02-03 15:38 UTC, mohamedmezlini commented
On fait les merge  sur la branch `develop`

2023-02-09 14:18 UTC, guillaumeprost commented on src/Controller/MemberController.php
> +    public function uploadFileToMember(UploadedFile $file, Member $member, string $documentType)
manque le type de retour

2023-02-09 14:34 UTC, guillaumeprost commented on src/Controller/MemberController.php
>      {
Tu peux ajouter un typage des attributs sur les fonctions ?

2023-02-09 14:35 UTC, guillaumeprost commented on src/Controller/MemberController.php
> +        $newFilename = md5(uniqid()) . '.' . $file->guessExtension();
J'aouterais ça à un FileService plutôt que le controller

2023-02-09 14:36 UTC, guillaumeprost commented on src/Entity/Member.php
> +    private $medicalCertificate;
manque le type

2023-02-09 14:36 UTC, guillaumeprost commented on src/Entity/Member.php
> +    private bool $exitPermit;
?bool si ils sont nullable

2023-02-09 14:37 UTC, guillaumeprost commented on src/Entity/Member.php
> +    public function setExitPermit(bool $exitPermit): self
Attention si il est nullable

2023-02-09 14:40 UTC, guillaumeprost commented on src/Form/MemberType.php
>              ->add('submit', SubmitType::class, [
D'après le bonne pratiques le bouton ne s'ajoute pas la définition du formulaire 
https://symfony.com/doc/6.3/best_practices.html#add-form-buttons-in-templates

2023-02-09 15:22 UTC, Anthony-Boulch-Celad commented on src/Entity/Member.php
> +    private $medicalCertificate;
+ du coup ?string car nullable

2023-02-09 15:36 UTC, Anthony-Boulch-Celad commented on src/Entity/Member.php
> +    public function setExitPermit(bool $exitPermit): self
J'ai fait quelque changement à ce niveau car bizarre de laisser un bool nullable donc j'ai passé not nullable :)

2023-02-10 10:55 UTC, Anthony-Boulch-Celad commented on src/Controller/MemberController.php
> +        $newFilename = md5(uniqid()) . '.' . $file->guessExtension();
J'ai rendu ça générique pour l'upload de fichier dans un FileService

2023-02-10 14:57 UTC, Anthony-Boulch-Celad commented on src/Controller/MemberController.php
> +                $this->addFlash('danger', 'Un problème est apparu en créant votre adhésion, veuillez réessayer plus tard');
Je ne sais pas trop pour le moment

2023-02-13 10:31 UTC, merged