switch attributes to all entities
stephtkd/tkkd pull request #132
Opened 2023-02-09 09:34 UTC by guillaumeprost

2023-02-09 14:52 UTC, Anthony-Boulch-Celad requested changes
Au cas où. Juste pour poser la discussion 😄

2023-02-09 14:52 UTC, Anthony-Boulch-Celad commented on src/Entity/AlbumPicture.php
> +    #[ORM\Column]
Un Assert en plus sur le lenght 255 serait nécessaire non ?

2023-02-09 14:52 UTC, Anthony-Boulch-Celad commented on src/Entity/AlbumPicture.php
> +    #[ORM\Column]
Peut-être à en reparler pour vérifier qu'au niveau des entités c'est ok 👌 au niveau des Assert

2023-02-10 15:52 UTC, guillaumeprost commented on src/Entity/AlbumPicture.php
> +    #[ORM\Column]
le length max est par default a 255 et puis il y a peu de chance que ce soit dépassé je pense

2023-02-13 09:33 UTC, merged