Formulaire création compte membre
stephtkd/tkkd pull request #82
Opened 2022-12-07 11:27 UTC by faissal35

2022-12-07 13:28 UTC, manekineko17 requested changes

2022-12-07 13:28 UTC, manekineko17 commented on src/Entity/User.php
> + * @UniqueEntity(fields={"email"}, message="Il existe déjà un compte avec cet adresse mail")
cette

2022-12-07 13:28 UTC, manekineko17 commented on src/Form/RegistrationFormType.php
> +                        'message' => 'Votre mot de passe doit contenir au moins 6 caractères, un chiffre, un majuscule et une minuscule.',
dont

2022-12-07 14:17 UTC, faissal35 commented on src/Entity/User.php
> + * @UniqueEntity(fields={"email"}, message="Il existe déjà un compte avec cet adresse mail")
c'est corrigé

2022-12-07 14:17 UTC, faissal35 commented on src/Form/RegistrationFormType.php
> +                        'message' => 'Votre mot de passe doit contenir au moins 6 caractères, un chiffre, un majuscule et une minuscule.',
c'est corrigé

2022-12-08 09:38 UTC, manekineko17 approved these changes

2022-12-08 09:38 UTC, merged